[tool.black]
line-length = 88
target-version = ['py310']
verbose = true

[tool.pytest.ini_options]
pythonpath = ['src/python']
testpaths = [
    'tests'
]

[tool.coverage.paths]
source = ["src/python/"]

[tool.coverage.run]
branch = true
source = ["src/python/"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "@abstractmethod"
    ]

[tool.isort]
profile = "black"

[tool.mypy]
pretty = "True"
python_version = "3.10"
mypy_path = "./src/python/"
exclude = "^tests/"
check_untyped_defs = 'True'
disallow_any_generics = 'True'
disallow_incomplete_defs = 'True'
disallow_subclassing_any = 'True'
disallow_untyped_calls = 'True'
disallow_untyped_decorators = 'True'
disallow_untyped_defs = 'True'
local_partial_types = 'True'
#no_implicit_optional = 'True'
no_implicit_reexport = 'True'
no_warn_no_return = 'True'
show_column_numbers = 'True'
show_error_codes = 'True'
show_error_context = 'True'
strict_equality = 'True'
warn_redundant_casts = 'True'
warn_return_any = 'True'
warn_unreachable = 'True'
warn_unused_configs = 'True'
warn_unused_ignores = 'True'
